---
- name: DNF Vagrant
  when: ansible_facts['distribution'] == "Fedora"
  dnf:
    name: vagrant
    state: latest

- name: YUM Vagrant
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != "Fedora"
  yum:
    name: vagrant
    state: latest

- name: APT Vagrant
  when: ansible_facts['os_family']|lower == 'debian'
  apt: 
    name: vagrant
    state: latest