#
#
#
#

Vagrant.configure("2") do |config|
    config.vm.box = "generic/fedora28"

    config.vm.define 'fedora' do |node|
        node.vm.hostname 'Logs.fedora.local'
        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "../ansible/Logs.yml"
	    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
        end
    end
end
