- name: "Installing Git (dnf)"
  when: ansible_facts['distribution'] == "Fedora"
  dnf:
    name: git
    state: present

- name: "Installing Git (yum)"
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != "Fedora"
  yum:
    name: git
    state: present

- name: "Installing Git (apt)"
  when: ansible_facts['os_family']|lower == 'debian'
  apt:
    name: git
    update_cache: yes
    state: present