- name: Making Directory
  file:
    path: /opt/Honeypot-Telnet-telnetLogger
    state: directory
    mode: 0775
    group: Honeypot-Group

- name: Git Actions For TelnetLogger Repo
  git:
   repo: "https://github.com/RealmOfTibbles/telnetlogger.git"
   dest: /opt/Honeypot-Telnet-telnetLogger/
   clone: yes
   update: yes
   force: yes
 

- name: Building Docker Image
  shell: docker build -t honeypot-telnetlogger /opt/Honeypot-Telnet-telnetLogger/
  args:
     chdir: /opt/Honeypot-Telnet-telnetLogger

- name: Run Container
  docker_container:
        name: Honeypot-Telnet-telnetLogger
        image: "honeypot-telnetlogger"
        state: started
        restart: yes
        ports:
        - "23:23"
        cpu_shares: 768
        memory: 512m
        cpu_period: 100000
        cpu_quota: 50000
        cap_drop:
        - all  
   
- name: Get Containers Details
  become: true
  shell: docker ps -l 
  register: Output

- name: Display Container Status's
  debug: var=Output.stdout_lines