---
- name: DNF Ansible
  when: ansible_facts['distribution'] == Fedora
  dnf:
    name: ansible
    state: latest

- name: YUM Ansible
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != Fedora
  yum:
    name: ansible
    state: latest

- name: APT Ansible
  when: ansible_facts['os_family']|lower == 'debian'
  apt: 
    name: ansible
    state: latest